name: Netflix Clone wih Github Actions
on: workflow_dispatch
env: 
    AWS_REGION: us-east-2

jobs:
    Testing:
        runs-on: ubuntu-latest
        steps:
            - name: Code checkout
              uses: actions/checkout@v4

            - name: Setup SonarQube
              uses: warchant/setup-sonar-scanner@v7

            - name: SonarQube Scan
              run: sonar-scanner
                -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
                -Dsonar.login=${{ secrets.SONAR_TOKEN }}
                -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
                -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
                -Dsonar.sources=src/
                -Dsonar.junit.reportsPath=target/surefire-reports/ 
                -Dsonar.jacoco.reportsPath=target/jacoco.exec 
                -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml
                -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/
            
            - name: SonarQube Quality Gate check
              id: sonarqube-quality-gate-check
              uses: sonarsource/sonarqube-quality-gate-action@master
            # Force to fail step after specific time.
              timeout-minutes: 5
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL}} #OPTIONAL 

#    Build-and-publish:
#        runs-on: ubuntu-latest
#        needs: Testing
#        steps:
#            - name: Code checkout
#              uses: actions/checkout@v4
#
#            - name: Set up QEMU
#              uses: docker/setup-qemu-action@v3
#
#            - name: Set up Docker Buildx
#              uses: docker/setup-buildx-action@v3
#
#            - name: Login to Docker Hub
#              uses: docker/login-action@v3
#              with:
#                username: ${{ secrets.DOCKERHUB_USERNAME }}
#                password: ${{ secrets.DOCKERHUB_TOKEN }}

#            - name: Build and push
#              uses: docker/build-push-action@v5
#              with:
#                push: true
#                tags: ndzenyuy/neflix:latest

    Deploy-to-kubernetes:        
        runs-on: ubuntu-latest
#        needs: Build-and-publish
        steps:
            - name: Code checkout
              uses: actions/checkout@v4

            - name: setup kube tools
              uses: yokawasa/action-setup-kube-tools@v0.11.0
                      

            - name: get Config file
              run: mkdir .kube && cd .kube && wget https://neflix-clone.s3.amazonaws.com/config
            
            - name: deploy to onecloud
              run: |
                kubectl apply -f deployment.yml
                kubectl apply -f service.yml


            

            